# Generated by Django 5.1.4 on 2025-02-13 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_lounge', models.IntegerField()),
                ('model_pop', models.IntegerField()),
                ('model_sport', models.IntegerField()),
                ('previous_owners', models.IntegerField()),
                ('km', models.IntegerField()),
                ('engine_power', models.IntegerField()),
                ('age_in_days', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('price', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
